// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace IstanbulCoders.Meetup.Grpc {
  public static partial class PhoneBookService
  {
    static readonly string __ServiceName = "IstanbulCoders.Meetup.Grpc.PhoneBookService";

    static readonly grpc::Marshaller<global::IstanbulCoders.Meetup.Grpc.Person> __Marshaller_Person = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::IstanbulCoders.Meetup.Grpc.Person.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::IstanbulCoders.Meetup.Grpc.AddPersonReply> __Marshaller_AddPersonReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::IstanbulCoders.Meetup.Grpc.AddPersonReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::IstanbulCoders.Meetup.Grpc.Empty> __Marshaller_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::IstanbulCoders.Meetup.Grpc.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::IstanbulCoders.Meetup.Grpc.AddressBook> __Marshaller_AddressBook = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::IstanbulCoders.Meetup.Grpc.AddressBook.Parser.ParseFrom);

    static readonly grpc::Method<global::IstanbulCoders.Meetup.Grpc.Person, global::IstanbulCoders.Meetup.Grpc.AddPersonReply> __Method_AddPerson = new grpc::Method<global::IstanbulCoders.Meetup.Grpc.Person, global::IstanbulCoders.Meetup.Grpc.AddPersonReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddPerson",
        __Marshaller_Person,
        __Marshaller_AddPersonReply);

    static readonly grpc::Method<global::IstanbulCoders.Meetup.Grpc.Empty, global::IstanbulCoders.Meetup.Grpc.AddressBook> __Method_GetPhoneBook = new grpc::Method<global::IstanbulCoders.Meetup.Grpc.Empty, global::IstanbulCoders.Meetup.Grpc.AddressBook>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetPhoneBook",
        __Marshaller_Empty,
        __Marshaller_AddressBook);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::IstanbulCoders.Meetup.Grpc.AddressbookReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PhoneBookService</summary>
    public abstract partial class PhoneBookServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::IstanbulCoders.Meetup.Grpc.AddPersonReply> AddPerson(global::IstanbulCoders.Meetup.Grpc.Person request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::IstanbulCoders.Meetup.Grpc.AddressBook> GetPhoneBook(global::IstanbulCoders.Meetup.Grpc.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PhoneBookService</summary>
    public partial class PhoneBookServiceClient : grpc::ClientBase<PhoneBookServiceClient>
    {
      /// <summary>Creates a new client for PhoneBookService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PhoneBookServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PhoneBookService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PhoneBookServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PhoneBookServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PhoneBookServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::IstanbulCoders.Meetup.Grpc.AddPersonReply AddPerson(global::IstanbulCoders.Meetup.Grpc.Person request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AddPerson(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::IstanbulCoders.Meetup.Grpc.AddPersonReply AddPerson(global::IstanbulCoders.Meetup.Grpc.Person request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddPerson, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::IstanbulCoders.Meetup.Grpc.AddPersonReply> AddPersonAsync(global::IstanbulCoders.Meetup.Grpc.Person request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AddPersonAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::IstanbulCoders.Meetup.Grpc.AddPersonReply> AddPersonAsync(global::IstanbulCoders.Meetup.Grpc.Person request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddPerson, null, options, request);
      }
      public virtual global::IstanbulCoders.Meetup.Grpc.AddressBook GetPhoneBook(global::IstanbulCoders.Meetup.Grpc.Empty request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetPhoneBook(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::IstanbulCoders.Meetup.Grpc.AddressBook GetPhoneBook(global::IstanbulCoders.Meetup.Grpc.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetPhoneBook, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::IstanbulCoders.Meetup.Grpc.AddressBook> GetPhoneBookAsync(global::IstanbulCoders.Meetup.Grpc.Empty request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetPhoneBookAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::IstanbulCoders.Meetup.Grpc.AddressBook> GetPhoneBookAsync(global::IstanbulCoders.Meetup.Grpc.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetPhoneBook, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PhoneBookServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PhoneBookServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PhoneBookServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddPerson, serviceImpl.AddPerson)
          .AddMethod(__Method_GetPhoneBook, serviceImpl.GetPhoneBook).Build();
    }

  }
}
#endregion
